# Generated by Django 5.0.4 on 2024-06-16 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppInventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controlcalidad',
            fields=[
                ('idcontrolcalidad', models.BigAutoField(primary_key=True, serialize=False, verbose_name='IDControlCalidad')),
                ('catacioncalidad', models.CharField(blank=True, max_length=30, null=True, verbose_name='CatacionCalidad')),
                ('registrocontrocalidadl', models.CharField(blank=True, max_length=30, null=True, verbose_name='RegistroControCalidadl')),
                ('hallazgoscalidad', models.CharField(blank=True, max_length=30, null=True, verbose_name='HallazgosCalidad')),
                ('fechavencimiento', models.DateField(blank=True, max_length=20, null=True, verbose_name='FechaVencimiento')),
            ],
            options={
                'verbose_name': 'Control Calidades',
                'verbose_name_plural': 'Control Calidad',
                'db_table': 'controlcalidad',
            },
        ),
        migrations.CreateModel(
            name='Fichaproduccion',
            fields=[
                ('idfichaproduccion', models.BigAutoField(primary_key=True, serialize=False, verbose_name='IDFichaProduccion')),
                ('cantidadproduccion', models.IntegerField(blank=True, null=True, verbose_name='CantidadProduccion')),
                ('medirclorado', models.CharField(blank=True, max_length=30, null=True, verbose_name='MedirClorado')),
                ('medirph', models.CharField(blank=True, max_length=30, null=True, verbose_name='MedirPH')),
                ('filtrado', models.CharField(blank=True, max_length=30, null=True, verbose_name='Filtrado')),
                ('microfiltrado', models.CharField(blank=True, max_length=30, null=True, verbose_name='Microfiltrado')),
                ('empaque', models.CharField(blank=True, max_length=30, null=True, verbose_name='Empaque')),
                ('fecha_produccion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fecha_produccion')),
                ('hora_produccion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hora_produccion')),
                ('num_lote_produccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Num_lote_produccion')),
                ('estadoproduccion', models.CharField(choices=[('Cumple', 'Cumple'), ('No Cumple', 'No Cumple')], help_text='Seleccione el estado de la producción', max_length=20, null=True)),
                ('idcontrolcalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduccion.controlcalidad', verbose_name='IDControlCalidad')),
                ('idproducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppInventario.producto', verbose_name='IDProducto')),
            ],
            options={
                'verbose_name': 'Fichas Producción',
                'verbose_name_plural': 'Ficha Producción',
                'db_table': 'fichaproduccion',
            },
        ),
    ]
