# Generated by Django 5.0.4 on 2024-07-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichaproduccion',
            options={'verbose_name': 'Ficha Producción', 'verbose_name_plural': 'Fichas Producción'},
        ),
        migrations.AlterField(
            model_name='fichaproduccion',
            name='cantidadproduccion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichaproduccion',
            name='empaque',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaproduccion',
            name='estadoproduccion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaproduccion',
            name='fecha_produccion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichaproduccion',
            name='filtrado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaproduccion',
            name='hora_produccion',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichaproduccion',
            name='idfichaproduccion',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fichaproduccion',
            name='medirclorado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaproduccion',
            name='medirph',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaproduccion',
            name='microfiltrado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichaproduccion',
            name='num_lote_produccion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
