# Generated by Django 5.0.6 on 2024-07-28 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppVentas', '0004_alter_pedidos_iddomicilio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCarrito',
            fields=[
                ('idpedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario_pedido', models.CharField(blank=True, max_length=20, null=True)),
                ('direccionpedido', models.CharField(blank=True, max_length=50, null=True)),
                ('telefonopedido', models.CharField(blank=True, max_length=20, null=True)),
                ('fechapedido', models.DateField(auto_now_add=True)),
                ('horapedido', models.TimeField(auto_now_add=True)),
                ('estadopedido', models.CharField(choices=[('Enviado', 'Enviado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado')], max_length=20, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('producto', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precioproductoinv', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('iddomicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppVentas.domicilio', verbose_name='ID Domicilio')),
            ],
            options={
                'verbose_name': 'PedidoCarrito',
                'verbose_name_plural': 'PedidosCarrito',
                'db_table': 'pedidoscarrito',
            },
        ),
    ]
