# Generated by Django 5.0.6 on 2024-07-28 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0001_initial'),
        ('AppVentas', '0004_alter_pedidos_iddomicilio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocarrito',
            name='iddomicilio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppVentas.domicilio', verbose_name='ID Domicilio'),
        ),
    ]
