# Generated by Django 5.0.4 on 2024-09-15 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarrito', '0005_alter_pedidocarrito_idusuario'),
        ('AppInventario', '0004_entradas_idinsumo_alter_controlinventario_identrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.IntegerField(blank=True, null=True, verbose_name='Precioproductoinv')),
                ('foto_producto', models.ImageField(upload_to='productos/')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCarrito.cart')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario.producto')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='productos',
            field=models.ManyToManyField(through='AppCarrito.CartItem', to='AppInventario.producto'),
        ),
        migrations.DeleteModel(
            name='PedidoCarrito',
        ),
    ]
