services:
  db:
    image: mysql:8.0
    container_name: mysql_cont
    restart: always
    volumes:
      - data:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: V3r02011
      MYSQL_DATABASE: dbh2o
      MYSQL_USER: myuser
      MYSQL_PASSWORD: Ubuntu08-
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 2

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delacascada
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
      python3 manage.py migrate --noinput && 
      python3 manage.py collectstatic --noinput && 
      python3 manage.py runserver 0.0.0.0:8000
      "

volumes:
  data: