FROM python:3.10

# Set environment variables
#ENV PYTHONDONTWRITEBYTECODE 1
#ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /code

# Install dependencies
COPY requirements.txt /code

RUN pip install -r requirements.txt
RUN pip install --upgrade pip

# Copy the project code into the container
COPY . .

EXPOSE 8000

# Run migrations and start the Django server
CMD ["sh", "-c", "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python3 manage.py runserver 0.0.0.0:8000"]
