apiVersion: apps/v1
kind: Deployment
metadata:
  name: delacascada-backend-dpl
  namespace: default
  labels:
    app: delacascada-backend-dpl
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delacascada-backend-dpl
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: delacascada-backend-dpl
        tier: frontend
    spec:
      containers:
        - name: delacascada-backend
          image: htijaro/delacascada-backend
          resources:
            requests:
              memory: "500Mi"
          command: ["sh", "-c"]
          args:
            - |
              sleep 60;
              python manage.py migrate;
              python manage.py runserver 0.0.0.0:8000;
          env:
            - name: DATABASE_NAME
              value: "dbh2o"
            - name: DATABASE_USER
              value: "myuser"
            - name: DATABASE_PASSWORD
              value: "ubuntu08-"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8000

        - name: deployment-mysql
          image: htijaro/mysql:8.0
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "500Mi"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "V3r02011$"
            - name: MYSQL_DATABASE
              value: "dbh2o"
            - name: MYSQL_USER
              value: "myuser"
            - name: MYSQL_PASSWORD
              value: "ubuntu08-"
            - name: MYSQL_HOST
              value: "mysql-service"  
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-volume
          hostPath:
            path: /mnt/data/mysql
            type: DirectoryOrCreate  

