apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
  labels:
    app: delacascada-backend-dpl
    tier: database
spec:
  type: NodePort
  ports:
  - targetPort: 3307
    port: 3307
    nodePort: 30009
  selector:
    app: delacascada-backend-dpl
    tier: database


