apiVersion: v1
kind: Service
metadata:
  name: delacascada-svc2
  labels:
    app: delacascada-backend-2
    tier: frontend
spec:
  type: NodePort
  ports:
  - targetPort: 8000
    port: 8000
    nodePort: 30008  
  selector:
    app: delacascada-backend-2
    tier: frontend



