# Generated by Django 5.0.4 on 2024-06-16 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('identradas', models.BigAutoField(primary_key=True, serialize=False, verbose_name='IDentradas')),
                ('nombreinsumoentrada', models.CharField(blank=True, max_length=50, null=True, verbose_name='NombreInsumoEntrada')),
                ('cantidadinsumoentrada', models.IntegerField(blank=True, null=True, verbose_name='CantidadInsumoEntrada')),
                ('fechainsumoentrada', models.DateField(blank=True, max_length=20, null=True, verbose_name='FechaInsumoEntrada')),
                ('horainsumoentrada', models.TimeField(blank=True, max_length=20, null=True, verbose_name='HoraInsumoEntrada')),
            ],
            options={
                'verbose_name': 'Entradas',
                'verbose_name_plural': 'Entrada',
                'db_table': 'entradas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreproductoinv', models.CharField(blank=True, max_length=100, null=True, verbose_name='NombreProductoInv')),
                ('cantidadproducto', models.IntegerField(blank=True, null=True, verbose_name='CantidadProducto')),
                ('precioproductoinv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PrecioProductoInv')),
                ('fechaactualizacioninv', models.DateField(blank=True, max_length=20, null=True, verbose_name='FechaActualizacionInv')),
                ('otrosdatos', models.CharField(blank=True, max_length=100, null=True, verbose_name='OtrosDatos')),
                ('presentacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Presentacion')),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'Productos',
                'verbose_name_plural': 'Producto',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idproveedores', models.BigAutoField(primary_key=True, serialize=False, verbose_name='IDProveedores')),
                ('num_proveedor', models.IntegerField(null=True, unique=True, verbose_name='Número Proveedor')),
                ('nombreproveedor', models.CharField(blank=True, max_length=50, null=True, verbose_name='NombreProveedor')),
                ('emailproveedor', models.CharField(blank=True, max_length=50, null=True, verbose_name='EmailProveedor')),
            ],
            options={
                'verbose_name': 'Proveedores',
                'verbose_name_plural': 'Proveedor',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('idsalida', models.BigAutoField(primary_key=True, serialize=False, verbose_name='IDsalida')),
                ('nombreproductosalida', models.CharField(blank=True, max_length=30, null=True, verbose_name='NombreProductoSalida')),
                ('cantidadproductosalida', models.IntegerField(blank=True, null=True, verbose_name='CantidadProductoSalida')),
                ('fechasalidaproducto', models.DateField(blank=True, max_length=10, null=True, verbose_name='FechaSalidaProducto')),
                ('horasalidaproducto', models.TimeField(blank=True, max_length=45, null=True, verbose_name='HoraSalidaProducto')),
            ],
            options={
                'verbose_name': 'Salidas',
                'verbose_name_plural': 'Salida',
                'db_table': 'salida',
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('idinsumos', models.BigAutoField(primary_key=True, serialize=False, verbose_name='IDInsumos')),
                ('nombreinsumo', models.CharField(blank=True, max_length=30, null=True, verbose_name='NombreInsumo')),
                ('cantidadinsumo', models.IntegerField(blank=True, null=True, verbose_name='CantidadInsumo')),
                ('idestadoinsumo', models.BooleanField(choices=[('Disponible', 'Disponible'), ('Agotado', 'Agotado')], help_text='Seleccione el Estado del Insumo', null=True)),
                ('idproveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario.proveedores', verbose_name='IDProveedor')),
            ],
            options={
                'verbose_name': 'Insumos',
                'verbose_name_plural': 'Insumo',
                'db_table': 'insumos',
            },
        ),
        migrations.CreateModel(
            name='Controlinventario',
            fields=[
                ('idinventario', models.BigAutoField(primary_key=True, serialize=False, verbose_name='IDInventario')),
                ('almacenajeproductos', models.CharField(blank=True, choices=[('Bodega1', 'Bodega1'), ('Bodega2', 'Bodega2'), ('Bodega3', 'Bodega3')], help_text='Seleccione la ubicación de los productos', max_length=50, null=True, verbose_name='AlmacenajeProductos')),
                ('solicitudcompra', models.CharField(blank=True, max_length=50, null=True, verbose_name='SolicitudCompra')),
                ('identrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario.entradas', verbose_name='IDEntrada')),
                ('idinsumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario.insumos', verbose_name='IDInsumo')),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInventario.producto', verbose_name='IDProducto')),
                ('idsalida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppInventario.salida', verbose_name='IDSalida')),
            ],
            options={
                'verbose_name': 'Inventarios',
                'verbose_name_plural': 'Inventario',
                'db_table': 'controlinventario',
            },
        ),
    ]
