# Generated by Django 5.0.4 on 2024-07-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0002_alter_producto_precioproductoinv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradas',
            old_name='identradas',
            new_name='identrada',
        ),
        migrations.RenameField(
            model_name='insumos',
            old_name='idinsumos',
            new_name='idinsumo',
        ),
        migrations.RenameField(
            model_name='proveedores',
            old_name='idproveedores',
            new_name='idproveedor',
        ),
    ]
