# Generated by Django 5.0.4 on 2024-07-27 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0003_rename_identradas_entradas_identrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='idinsumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppInventario.insumos', verbose_name='IDProveedor'),
        ),
        migrations.AlterField(
            model_name='controlinventario',
            name='identrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppInventario.entradas', verbose_name='IDEntrada'),
        ),
        migrations.AlterField(
            model_name='controlinventario',
            name='idinsumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppInventario.insumos', verbose_name='IDInsumo'),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='idproveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppInventario.proveedores', verbose_name='IDProveedor'),
        ),
    ]
