# Generated by Django 5.0.4 on 2024-11-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0004_entradas_idinsumo_alter_controlinventario_identrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
