# Generated by Django 5.0.4 on 2024-11-17 02:42

from django.db import migrations

def add_initial_data(apps, schema_editor):
    Producto = apps.get_model('AppInventario', 'Producto')

    # Inserta los datos fijos
    Producto.objects.bulk_create([
        Producto(idproducto=1, nombreproductoinv='Botella 250 ml', cantidadproducto=5000, precioproductoinv=600,
                 fechaactualizacioninv='2024-07-28', presentacion='250 ml', foto_producto='media/B250ml.jpg'),
        Producto(idproducto=2, nombreproductoinv='Botella 330 ml', cantidadproducto=4000, precioproductoinv=1000,
                 fechaactualizacioninv='2024-07-28', presentacion='330 ml', foto_producto='media/B330ml.jpg'),
        Producto(idproducto=3, nombreproductoinv='Botella 600 ml', cantidadproducto=4900, precioproductoinv=1300,
                 fechaactualizacioninv='2024-07-28', presentacion='600 ml', foto_producto='media/B600ml.jpg'),
        Producto(idproducto=4, nombreproductoinv='Bolsa 6 L', cantidadproducto=3500, precioproductoinv=6500,
                 fechaactualizacioninv='2024-07-28', presentacion='6 L', foto_producto='media/B6L.jpg'),
        Producto(idproducto=5, nombreproductoinv='Botellón 20 L', cantidadproducto=850, precioproductoinv=18000,
                 fechaactualizacioninv='2024-07-28', presentacion='20 L', foto_producto='media/B20L.jpg'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0005_alter_producto_foto_producto'),  # Asegúrate de que esta dependencia es correcta
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]

