# Generated by Django 5.0.4 on 2024-06-16 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('iddomicilio', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechadomicilio', models.DateField(auto_now_add=True)),
                ('horadomicilio', models.TimeField(auto_now_add=True)),
                ('estadodomicilio', models.CharField(choices=[('Entregado', 'Entregado'), ('Pendiente', 'Pendiente'), ('Devuelto', 'Devuelto'), ('Cancelado', 'Cancelado')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
                'db_table': 'domicilio',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('idpedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario_pedido', models.CharField(blank=True, max_length=20, null=True)),
                ('direccionpedido', models.CharField(blank=True, max_length=50, null=True)),
                ('telefonopedido', models.CharField(blank=True, max_length=20, null=True)),
                ('fechapedido', models.DateField(auto_now_add=True)),
                ('horapedido', models.TimeField(auto_now_add=True)),
                ('estadopedido', models.CharField(choices=[('Entregado', 'Entregado'), ('Pendiente', 'Pendiente'), ('Devuelto', 'Devuelto'), ('Cancelado', 'Cancelado')], max_length=20, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('iddomicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppVentas.domicilio')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idventa', models.BigAutoField(primary_key=True, serialize=False)),
                ('idfactura', models.CharField(blank=True, max_length=45, null=True, verbose_name='IDventa')),
                ('fechaventa', models.DateField()),
                ('horaventa', models.CharField(blank=True, max_length=10, null=True, verbose_name='IDventa')),
                ('nombre_usuario', models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombre Usuario')),
                ('idpedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppVentas.pedidos')),
            ],
            options={
                'verbose_name': 'Ventas',
                'verbose_name_plural': 'Venta',
                'db_table': 'ventas',
            },
        ),
    ]
