# Generated by Django 5.0.6 on 2024-06-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estadopedido',
            field=models.CharField(choices=[('Enviado', 'Enviado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado')], max_length=20, null=True),
        ),
    ]
