# Generated by Django 5.0.6 on 2024-06-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVentas', '0002_alter_pedidos_estadopedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='precioproductoinv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='producto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
