# Generated by Django 5.0.6 on 2024-07-10 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVentas', '0003_pedidos_cantidad_pedidos_precioproductoinv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='iddomicilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppVentas.domicilio', verbose_name='ID Domicilio'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='precioproductoinv',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
