# Generated by Django 5.0.4 on 2024-07-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVentas', '0004_alter_pedidos_iddomicilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='numdomicilio',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
