# Generated by Django 5.0.4 on 2024-07-27 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVentas', '0006_remove_domicilio_numdomicilio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='iddomicilio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppVentas.domicilio', verbose_name='IDDomicilio'),
        ),
    ]
