# Generated by Django 5.0.4 on 2024-07-27 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVentas', '0008_alter_ventas_fechaventa_alter_ventas_horaventa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='iddomicilio',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='idpedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppVentas.pedidos', verbose_name='ID Pedido'),
        ),
    ]
