# Generated by Django 5.0.4 on 2024-09-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVentas', '0009_remove_pedidos_iddomicilio_domicilio_idpedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.CharField(max_length=20)),
            ],
        ),
    ]
